// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ORF_index
Rcpp::DataFrame ORF_index(SEXP Tags, SEXP Sequence, int trans_tab);
RcppExport SEXP _microseq_ORF_index(SEXP TagsSEXP, SEXP SequenceSEXP, SEXP trans_tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Tags(TagsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sequence(SequenceSEXP);
    Rcpp::traits::input_parameter< int >::type trans_tab(trans_tabSEXP);
    rcpp_result_gen = Rcpp::wrap(ORF_index(Tags, Sequence, trans_tab));
    return rcpp_result_gen;
END_RCPP
}
// extractSeq
SEXP extractSeq(SEXP Gseq, SEXP Left, SEXP Right, SEXP Strand);
RcppExport SEXP _microseq_extractSeq(SEXP GseqSEXP, SEXP LeftSEXP, SEXP RightSEXP, SEXP StrandSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Gseq(GseqSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Left(LeftSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Right(RightSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Strand(StrandSEXP);
    rcpp_result_gen = Rcpp::wrap(extractSeq(Gseq, Left, Right, Strand));
    return rcpp_result_gen;
END_RCPP
}
// revComp
CharacterVector revComp(CharacterVector Seq, bool rev);
RcppExport SEXP _microseq_revComp(SEXP SeqSEXP, SEXP revSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type Seq(SeqSEXP);
    Rcpp::traits::input_parameter< bool >::type rev(revSEXP);
    rcpp_result_gen = Rcpp::wrap(revComp(Seq, rev));
    return rcpp_result_gen;
END_RCPP
}
// transl
CharacterVector transl(CharacterVector Seq, int trans_tab);
RcppExport SEXP _microseq_transl(SEXP SeqSEXP, SEXP trans_tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type Seq(SeqSEXP);
    Rcpp::traits::input_parameter< int >::type trans_tab(trans_tabSEXP);
    rcpp_result_gen = Rcpp::wrap(transl(Seq, trans_tab));
    return rcpp_result_gen;
END_RCPP
}
