# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ORF_index <- function(Tags, Sequence, trans_tab) {
    .Call(`_microseq_ORF_index`, Tags, Sequence, trans_tab)
}

extractSeq <- function(Gseq, Left, Right, Strand) {
    .Call(`_microseq_extractSeq`, Gseq, Left, Right, Strand)
}

revComp <- function(Seq, rev) {
    .Call(`_microseq_revComp`, Seq, rev)
}

transl <- function(Seq, trans_tab) {
    .Call(`_microseq_transl`, Seq, trans_tab)
}

translCodon <- function(Seq) {
    .Call(`_microseq_translCodon`, Seq)
}

