# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_fastq <- function(path) {
    .Call('microseq_read_fastq', PACKAGE = 'microseq', path)
}

read_fastq_Sanger <- function(path) {
    .Call('microseq_read_fastq_Sanger', PACKAGE = 'microseq', path)
}

write_fastq <- function(header, sequence, quality, path) {
    .Call('microseq_write_fastq', PACKAGE = 'microseq', header, sequence, quality, path)
}

read_fasta <- function(path) {
    .Call('microseq_read_fasta', PACKAGE = 'microseq', path)
}

write_fasta <- function(header, sequence, path, width) {
    .Call('microseq_write_fasta', PACKAGE = 'microseq', header, sequence, path, width)
}

revComp <- function(Seq, rev) {
    .Call('microseq_revComp', PACKAGE = 'microseq', Seq, rev)
}

transl <- function(Seq) {
    .Call('microseq_transl', PACKAGE = 'microseq', Seq)
}

